INSERT INTO site.site(
        full_url,
        endpoint_path,
        protocol,
        params,
        page_extension,
        port,
        tl_domain,
        sub_domains,
        ipv4,
        ipv6
    )
VALUES(
        %(full_url)s,
        %(endpoint_path)s,
        %(protocol)s,
        %(params)s,
        %(page_extension)s,
        %(port)s,
        %(tl_domain)s,
        %(sub_domains)s,
        %(ipv4)s,
        %(ipv6)s
    );